apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    openshift.io/description: This configmap contains script which will make sure that cluster upgrade progressing true to execute test 
  name: post-sync
data:
{{- $root := . }}
{{- range $path, $content := .Files.Glob "files/post-sync-scripts/*" }}
{{ base $path | indent 2 }}: |-
{{ $root.Files.Get $path | indent 4}}
{{ end }}
